"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const hand_1 = require("../core/hand");
const wall_1 = require("../core/wall");
let t = (0, wall_1.constructReserve)();
(0, wall_1.printWall)(t);
console.log("\n");
let h = (0, hand_1.drawHand)(t);
console.log((0, hand_1.handToString)(h));
console.log("\n");
(0, wall_1.printWall)(t);
